### ISSUE TITLE
$HOSTADDRESS$ not parsed ? 

### ISSUE THREAD

**Issue by alex-leonhardt** [deanwilson/sysadmin-scripts#3]
Hi,

am using nrpe-runner and noticed that when I use $HOSTADDRESS$ it's unable to parse that data. any way around this / or is there a simple fix ? 

Alex

**Comment by deanwilson** [comment]
This only uses the literal commands from the nrpe configs. It doesn't have access to the nagios macros/vars and so can't expand things like $HOSTADDRESS$.
